#!/usr/bin/env python3
# Generic hook-registration renderer — shared by every environment adapter, exactly like
# dispatch.sh; nothing environment-specific lives in this file.
#
# An adapter's hooks.yaml is the SOURCE OF TRUTH for its firing surface, but it cannot be
# installed verbatim: the host executes a hook's `command` as a shell command line and
# resolves its `cwd` against $HOME by default, so both must be absolute by the time the host
# reads them. This script is that rendering stage.
#
# THREE render targets, one substitution path:
#   hooks.yaml        -> the workspace hook file, <dest>/safe-harness.json;
#   agent-hooks.yaml  -> a `hooks:` block in the frontmatter of one agent file per framework
#                        ORCHESTRATOR (the H0 session-started boundary, which the host reads
#                        per agent, never from the workspace file);
#   settings.yaml     -> the required workspace editor settings, MERGED into the workspace
#                        settings file. Without them the other two targets are inert: the
#                        host discovers hook files and does not execute them.
#
# Four placeholders are substituted:
#   {{ADAPTERS_DIR}}    this directory, derived from THIS FILE'S own location — `adapters/`
#                       ships in the harness repo, never in the framework, so anchoring the
#                       dispatch path on any environment variable would name a file that does
#                       not exist;
#   {{FRAMEWORK_DIR}}   the absolute framework root, supplied explicitly and required to exist.
#   {{AGENT_SLUG}}      the scoping orchestrator's slug (agent target only) — the trailing
#                       dispatch argument that carries the agent identity no payload names.
#   {{HOOKS_LOCATION}}  where the hooks file actually landed, as the host must be told to
#                       discover it (settings target only).
#
# Rendered hook output is machine-specific: it is generated at install time, never committed.
# The agent target writes into the DELIVERED agent copy and never the framework's committed
# sources; everything outside the managed block — frontmatter and body alike — is carried
# across byte for byte. The settings target writes into a file that IS committed and
# hand-maintained, so it merges keys and preserves everything else, including comments.
#
# Rendering is all-or-nothing — every output is validated in memory and files are written only
# once ALL THREE targets pass. A half-rendered registration is the failure this stage prevents.

import argparse
import json
import re
import shlex
import sys
from pathlib import Path

import yaml

RENDERED_FILENAME = "safe-harness.json"
AGENT_HOOKS_FILENAME = "agent-hooks.yaml"
SETTINGS_FILENAME = "settings.yaml"
_COMMAND_FIELD = "command"
_REQUIRED_FIELDS = ("type", "command", "cwd")
_PLACEHOLDER = re.compile(r"\{\{[^{}]*\}\}")
_HOOKS_KEY = "hooks"
_AGENT_HOOKS_KEY = "agentHooks"
_SETTINGS_KEY = "settings"
_SETTINGS_PATH_KEY = "path"
_SETTINGS_MERGE_KEY = "merge"
_ORCHESTRATOR_KEY = "orchestrator"
_WORKFLOW_GLOB = "*.workflow.conf.yaml"
_FENCE = "---"
_BLOCK_OPEN = "# >>> safe-harness H0 — generated by adapters/render_hooks.py; do not edit >>>"
_BLOCK_CLOSE = "# <<< safe-harness H0 <<<"


class RenderError(Exception):
    """A rendering refusal — reported to the operator, never written to disk."""


def _substitute(node, shell_values: dict, plain_values: dict, in_command: bool):
    if isinstance(node, dict):
        return {
            key: _substitute(value, shell_values, plain_values, key == _COMMAND_FIELD)
            for key, value in node.items()
        }
    if isinstance(node, list):
        return [_substitute(item, shell_values, plain_values, in_command) for item in node]
    if isinstance(node, str):
        rendered = node
        # A `command` is a shell command line; every other field is a literal path.
        for placeholder, value in (shell_values if in_command else plain_values).items():
            rendered = rendered.replace(placeholder, value)
        return rendered
    return node


def _no_leftover_placeholder(rendered: str, where: str) -> None:
    leftover = sorted(set(_PLACEHOLDER.findall(rendered)))
    if leftover:
        raise RenderError(
            f"unsubstituted placeholder(s) survived rendering {where}: "
            + ", ".join(leftover)
            + " — this renderer resolves only {{ADAPTERS_DIR}}, {{FRAMEWORK_DIR}}"
            + " and {{AGENT_SLUG}}"
        )


def _validate_hooks(hooks, where: str) -> None:
    if not isinstance(hooks, dict) or not hooks:
        raise RenderError(f"{where} has no '{_HOOKS_KEY}' object")

    for event, entries in hooks.items():
        if not isinstance(entries, list) or not entries:
            raise RenderError(f"hook '{event}' registers no command entry")
        for index, entry in enumerate(entries):
            location = f"hook entry {event}[{index}]"
            if not isinstance(entry, dict):
                raise RenderError(f"{location} is not an object")

            missing = [field for field in _REQUIRED_FIELDS if field not in entry]
            if missing:
                raise RenderError(
                    f"{location} is missing required field(s): {', '.join(missing)}"
                )

            cwd = Path(entry["cwd"])
            if not cwd.is_absolute():
                raise RenderError(f"{location} has a relative cwd: {entry['cwd']}")
            if not cwd.is_dir():
                raise RenderError(
                    f"{location} has a cwd that is not a directory: {entry['cwd']}"
                )

            argv = shlex.split(entry[_COMMAND_FIELD])
            if not argv:
                raise RenderError(f"{location} has an empty command")

            program = Path(argv[0])
            if not program.is_absolute():
                raise RenderError(f"{location} has a relative command path: {argv[0]}")
            if not program.is_file():
                raise RenderError(f"{location} names a command that does not exist: {argv[0]}")


def _validate(hook_map: dict) -> None:
    _no_leftover_placeholder(json.dumps(hook_map), "the workspace hook map")
    _validate_hooks(hook_map.get(_HOOKS_KEY), "the hook map")


def _load_source(path: Path, what: str) -> dict:
    if not path.is_file():
        raise RenderError(f"no {what} at {path}")

    source = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(source, dict):
        raise RenderError(f"the {what} at {path} is not an object")
    return source


def _substituted(source, adapters_dir: Path, framework_root: Path, slug: str | None = None):
    literals = {
        "{{ADAPTERS_DIR}}": str(adapters_dir),
        "{{FRAMEWORK_DIR}}": str(framework_root),
    }
    if slug is not None:
        literals["{{AGENT_SLUG}}"] = slug
    return _substitute(
        source,
        shell_values={key: shlex.quote(value) for key, value in literals.items()},
        plain_values=literals,
        in_command=False,
    )


def _require_dispatch(adapters_dir: Path) -> None:
    dispatch = adapters_dir / "dispatch.sh"
    if not dispatch.is_file():
        raise RenderError(f"no dispatch script at {dispatch}")


def render(hooks_source: Path, adapters_dir: Path, framework_root: Path) -> dict:
    _require_dispatch(adapters_dir)
    rendered = _substituted(
        _load_source(hooks_source, "hook map"), adapters_dir, framework_root
    )
    _validate(rendered)
    return rendered


def _orchestrator_slugs(workflows_dir: Path) -> list[str]:
    """An orchestrator is whoever the framework's own workflow catalog names as one — the
    adapter hardcodes no roster."""
    if not workflows_dir.is_dir():
        raise RenderError(
            f"no workflow catalog at {workflows_dir} — the orchestrator set the H0 "
            "registration follows is derived from it"
        )

    slugs = set()
    for path in sorted(workflows_dir.rglob(_WORKFLOW_GLOB)):
        workflow = yaml.safe_load(path.read_text(encoding="utf-8"))
        if not isinstance(workflow, dict):
            raise RenderError(f"the workflow at {path} is not an object")
        slug = workflow.get(_ORCHESTRATOR_KEY)
        if slug is not None:
            if not isinstance(slug, str) or not slug:
                raise RenderError(f"the workflow at {path} names a non-slug orchestrator")
            slugs.add(slug)

    if not slugs:
        raise RenderError(
            f"the workflow catalog at {workflows_dir} names no orchestrator — nothing "
            "would carry the H0 session-started registration and no session could open"
        )
    return sorted(slugs)


def _split_frontmatter(text: str, where: str) -> tuple[list[str], str]:
    lines = text.splitlines(keepends=True)
    if not lines or lines[0].strip() != _FENCE:
        raise RenderError(f"{where} has no YAML frontmatter to carry the hook block")

    for index in range(1, len(lines)):
        if lines[index].strip() == _FENCE:
            return lines[1:index], "".join(lines[index + 1 :])
    raise RenderError(f"{where} has a frontmatter block that is never closed")


def _without_managed_block(front: list[str], where: str) -> list[str]:
    kept: list[str] = []
    inside = False
    for line in front:
        marker = line.strip()
        if marker == _BLOCK_OPEN:
            if inside:
                raise RenderError(f"{where} carries a damaged managed hook block (nested)")
            inside = True
        elif marker == _BLOCK_CLOSE:
            if not inside:
                raise RenderError(f"{where} carries a damaged managed hook block (unopened)")
            inside = False
        elif not inside:
            kept.append(line)
    if inside:
        raise RenderError(f"{where} carries a damaged managed hook block (never closed)")
    return kept


def _render_agent(source_text: str, slug: str, hooks: dict, where: str) -> str:
    front, body = _split_frontmatter(source_text, where)
    front = _without_managed_block(front, where)

    declared = yaml.safe_load("".join(front)) or {}
    if not isinstance(declared, dict):
        raise RenderError(f"{where} has frontmatter that is not a YAML object")
    if _HOOKS_KEY in declared:
        raise RenderError(
            f"{where} already declares its own unmanaged '{_HOOKS_KEY}:' block — a second "
            "one would make the frontmatter a duplicate key the host rejects"
        )

    # `width` disables YAML line folding: a `command` is a shell command line the host runs
    # verbatim, and absolute paths routinely exceed the default 80-column fold.
    block = yaml.safe_dump(
        {_HOOKS_KEY: hooks},
        sort_keys=False,
        default_flow_style=False,
        allow_unicode=True,
        width=2**31 - 1,
    )
    rendered = (
        f"{_FENCE}\n"
        + "".join(front)
        + f"{_BLOCK_OPEN}\n"
        + block
        + f"{_BLOCK_CLOSE}\n"
        + f"{_FENCE}\n"
        + body
    )

    _no_leftover_placeholder(rendered, where)
    check_front, check_body = _split_frontmatter(rendered, where)
    parsed = yaml.safe_load("".join(check_front))
    if not isinstance(parsed, dict):
        raise RenderError(f"{where} rendered frontmatter that is not a YAML object")
    if parsed.get(_HOOKS_KEY) != hooks:
        raise RenderError(f"{where} rendered a hook block that does not match its source")
    if {key: value for key, value in parsed.items() if key != _HOOKS_KEY} != declared:
        raise RenderError(f"{where} rendered frontmatter that alters the agent's own keys")
    if check_body != body:
        raise RenderError(f"{where} rendered a body that differs from its source")
    _validate_hooks(hooks, where)
    return rendered


def render_agents(
    agent_hooks_source: Path,
    agents_dir: Path,
    agents_dest: Path,
    workflows_dir: Path,
    adapters_dir: Path,
    framework_root: Path,
) -> dict[Path, str]:
    """The H0 target: one rendered agent file per framework orchestrator, each carrying the
    agent-scoped `UserPromptSubmit` registration with its OWN slug as dispatch argument."""
    _require_dispatch(adapters_dir)

    source = _load_source(agent_hooks_source, "agent hook map")
    template = source.get(_AGENT_HOOKS_KEY)
    if not isinstance(template, dict) or not template:
        raise RenderError(
            f"the agent hook map at {agent_hooks_source} has no '{_AGENT_HOOKS_KEY}' object"
        )

    outputs: dict[Path, str] = {}
    for slug in _orchestrator_slugs(workflows_dir):
        agent_source = agents_dir / f"{slug}.agent.md"
        if not agent_source.is_file():
            raise RenderError(
                f"orchestrator '{slug}' has no agent file at {agent_source} — its "
                "session-started boundary would never fire"
            )
        hooks = _substituted(template, adapters_dir, framework_root, slug)
        outputs[agents_dest / f"{slug}.agent.md"] = _render_agent(
            agent_source.read_text(encoding="utf-8"), slug, hooks, str(agent_source)
        )
    return outputs


# The settings target — a MERGE into a file the OPERATOR owns.
#
# The other two targets are generated artifacts this renderer owns outright. The workspace
# settings file is not: it is committed, hand-maintained, and read by the host as JSONC
# (comments and trailing commas allowed). So it is edited textually, key by key — parsing and
# re-serialising it would silently delete the operator's comments and reflow their file, and
# a file that cannot be parsed is refused rather than replaced, because replacing it destroys
# settings that cannot be recovered.
#
# The keys carry no managed delimiter, unlike the H0 block: a delimiter marks a region this
# renderer may strip, and these are individual host settings in someone else's file.


def _scan_string(text: str, index: int) -> int:
    """The index just past the closing quote of the JSON string starting at `index`."""
    cursor = index + 1
    while cursor < len(text):
        if text[cursor] == "\\":
            cursor += 2
            continue
        if text[cursor] == '"':
            return cursor + 1
        cursor += 1
    raise RenderError("a string is never closed")


def _end_of_comment(text: str, index: int) -> int:
    if text[index + 1] == "/":
        end = text.find("\n", index)
        return len(text) if end == -1 else end
    end = text.find("*/", index + 2)
    if end == -1:
        raise RenderError("a block comment is never closed")
    return end + 2


def _is_comment(text: str, index: int) -> bool:
    return text[index] == "/" and index + 1 < len(text) and text[index + 1] in "/*"


def _skip_insignificant(text: str, index: int) -> int:
    while index < len(text):
        if text[index].isspace():
            index += 1
        elif _is_comment(text, index):
            index = _end_of_comment(text, index)
        else:
            return index
    return index


def _strict_json(text: str) -> str:
    """A JSONC projection onto strict JSON — comments blanked, trailing commas dropped —
    with every other byte, and every offset, left where it was."""
    out = list(text)
    index = 0
    last = -1
    while index < len(text):
        char = text[index]
        if char.isspace():
            index += 1
            continue
        if _is_comment(text, index):
            end = _end_of_comment(text, index)
            for position in range(index, end):
                if out[position] != "\n":
                    out[position] = " "
            index = end
            continue
        if char == '"':
            last = index
            index = _scan_string(text, index)
            continue
        if char in "}]" and last >= 0 and text[last] == ",":
            out[last] = " "
        last = index
        index += 1
    return "".join(out)


def _scan_value(text: str, index: int) -> int:
    """The index just past the JSON value starting at `index`."""
    if text[index] == '"':
        return _scan_string(text, index)
    if text[index] in "{[":
        depth = 0
        while index < len(text):
            char = text[index]
            if char == '"':
                index = _scan_string(text, index)
                continue
            if _is_comment(text, index):
                index = _end_of_comment(text, index)
                continue
            if char in "{[":
                depth += 1
            elif char in "}]":
                depth -= 1
                if depth == 0:
                    return index + 1
            index += 1
        raise RenderError("a value is never closed")
    while index < len(text) and text[index] not in ",}] \t\r\n" and not _is_comment(text, index):
        index += 1
    return index


def _top_level_members(text: str) -> tuple[int, list[tuple[str, int, int, int]]]:
    """The outermost object's opening brace, and one `(key, key_start, value_start,
    value_end)` per member — the spans a key-level edit rewrites."""
    index = _skip_insignificant(text, 0)
    if index >= len(text) or text[index] != "{":
        raise RenderError("the settings are not a JSON object")

    brace = index
    index = _skip_insignificant(text, index + 1)
    members: list[tuple[str, int, int, int]] = []
    while index < len(text) and text[index] != "}":
        if text[index] == ",":
            index = _skip_insignificant(text, index + 1)
            continue
        if text[index] != '"':
            raise RenderError("a settings key is not a quoted string")
        key_start = index
        key_end = _scan_string(text, index)
        index = _skip_insignificant(text, key_end)
        if index >= len(text) or text[index] != ":":
            raise RenderError("a settings key carries no value")
        index = _skip_insignificant(text, index + 1)
        value_start = index
        index = _scan_value(text, index)
        members.append((json.loads(text[key_start:key_end]), key_start, value_start, index))
        index = _skip_insignificant(text, index)
    return brace, members


def _line_indent(text: str, index: int) -> str:
    start = text.rfind("\n", 0, index) + 1
    return text[start:index] if not text[start:index].strip() else "  "


def _rendered_value(value, indent: str) -> str:
    rendered = json.dumps(value, indent=2)
    head, *rest = rendered.splitlines()
    return "\n".join([head] + [indent + line for line in rest])


def _spliced(text: str, updates: dict) -> str:
    """The same file with ONLY the given keys' values rewritten (or added) — every other
    byte, comment and indentation included, exactly where it was."""
    brace, members = _top_level_members(text)
    spans = {key: (key_start, value_start, value_end) for key, key_start, value_start, value_end in members}
    indent = _line_indent(text, members[0][1]) if members else "  "

    replacements = []
    additions = []
    for key, value in updates.items():
        if key in spans:
            key_start, value_start, value_end = spans[key]
            replacements.append((value_start, value_end, _rendered_value(value, _line_indent(text, key_start))))
        else:
            additions.append(f"{indent}{json.dumps(key)}: {_rendered_value(value, indent)}")

    for start, end, rendered in sorted(replacements, reverse=True):
        text = text[:start] + rendered + text[end:]

    if additions:
        joined = ",\n".join(additions)
        chunk = f"\n{joined}," if members else f"\n{joined}\n"
        text = text[: brace + 1] + chunk + text[brace + 1 :]
    return text


def _merged(existing: dict, key: str, required):
    """A required object value is merged one level deep: the host reads
    `chat.hookFilesLocations` as a discovery SET, so this adapter's entry joins whatever
    else is registered rather than displacing it."""
    if not isinstance(required, dict):
        return required
    current = existing.get(key)
    if current is None:
        return dict(required)
    if not isinstance(current, dict):
        raise RenderError(
            f"the workspace settings already set '{key}' to a {type(current).__name__} — "
            "the host reads it as an object and discards anything else. This renderer "
            "merges into that setting rather than replacing a value the operator chose, "
            "so correct or remove it and re-run"
        )
    return {**current, **required}


def _render_settings_text(source_text: str | None, required: dict, where: str) -> str | None:
    """The settings file's new contents, or None when every required setting already holds."""
    if source_text is None or not _strict_json(source_text).strip():
        return json.dumps(required, indent=2) + "\n"

    try:
        existing = json.loads(_strict_json(source_text))
    except ValueError as error:
        raise RenderError(
            f"the workspace settings at {where} cannot be parsed ({error}) — they are "
            "hand-maintained and this renderer will not replace a file whose contents it "
            "cannot preserve; repair the file and re-run"
        ) from error
    if not isinstance(existing, dict):
        raise RenderError(
            f"the workspace settings at {where} are not a JSON object — there is nowhere "
            "to carry a setting, and overwriting the file would discard whatever it means"
        )

    updates = {key: _merged(existing, key, value) for key, value in required.items()}
    if all(existing.get(key) == value for key, value in updates.items()):
        return None

    rendered = _spliced(source_text, updates)
    if json.loads(_strict_json(rendered)) != {**existing, **updates}:
        raise RenderError(f"rendering {where} altered a setting that was not required")
    return rendered


def _hooks_location(hooks_dest: Path, framework_root: Path) -> str:
    """Where the host must be told to look — workspace-relative when the hooks file landed
    inside the framework workspace, absolute when it did not, never the default restated."""
    resolved = hooks_dest.resolve()
    try:
        return resolved.relative_to(framework_root).as_posix()
    except ValueError:
        return resolved.as_posix()


def _substituted_settings(node, literals: dict):
    """Substitution over KEYS as well as values — the hooks location is a key of the
    discovery map, not a value."""
    if isinstance(node, dict):
        return {
            _substituted_settings(key, literals): _substituted_settings(value, literals)
            for key, value in node.items()
        }
    if isinstance(node, list):
        return [_substituted_settings(item, literals) for item in node]
    if isinstance(node, str):
        for placeholder, value in literals.items():
            node = node.replace(placeholder, value)
        return node
    return node


def render_settings(
    settings_source: Path,
    framework_root: Path,
    hooks_dest: Path,
    settings_dest: Path | None = None,
) -> tuple[Path, str | None]:
    """The settings target: the file the required settings belong in, and its new contents
    — or None when it already carries them."""
    source = _load_source(settings_source, "settings map")
    declared = source.get(_SETTINGS_KEY)
    if not isinstance(declared, dict):
        raise RenderError(
            f"the settings map at {settings_source} has no '{_SETTINGS_KEY}' object"
        )

    relative = declared.get(_SETTINGS_PATH_KEY)
    required = declared.get(_SETTINGS_MERGE_KEY)
    if not isinstance(relative, str) or not relative or Path(relative).is_absolute():
        raise RenderError(
            f"the settings map at {settings_source} names no workspace-relative "
            f"'{_SETTINGS_PATH_KEY}' to merge into"
        )
    if not isinstance(required, dict) or not required:
        raise RenderError(
            f"the settings map at {settings_source} requires no setting — without "
            "'chat.useHooks' the host discovers every rendered hook and executes none"
        )

    required = _substituted_settings(
        required, {"{{HOOKS_LOCATION}}": _hooks_location(hooks_dest, framework_root)}
    )
    _no_leftover_placeholder(json.dumps(required), "the workspace settings")

    target = (
        settings_dest / Path(relative).name
        if settings_dest is not None
        else framework_root / relative
    )
    source_text = target.read_text(encoding="utf-8") if target.is_file() else None
    return target, _render_settings_text(source_text, required, str(target))


def _resolve_agents_dir(explicit: str | None, bundle: str | None, role: str) -> Path:
    """Where the H0 block is injected. There is NO framework-anchored default: a framework
    ships its agents through a host bundle, so writing a second copy elsewhere would put the
    same agent in front of the host twice — once carrying the hook, once carrying the
    bundle's own tool restrictions — and which one wins is not something this renderer can
    know. It refuses to guess instead."""
    if explicit:
        return Path(explicit)
    if bundle:
        root = Path(bundle).expanduser()
        if not root.is_dir():
            raise RenderError(f"the bundle root does not exist: {root}")
        return root.resolve() / "agents"
    raise RenderError(
        f"no agent directory to be {role} — the H0 registration is injected into the "
        "DELIVERED agents, so pass --bundle-dir <bundle root> after the framework's own "
        "bundle renderer has run, or name --agents-dir/--agents-dest explicitly for a "
        "framework delivered some other way. Defaulting would install a second copy of "
        "every orchestrator alongside the delivered one"
    )


def _resolve_framework_root(raw: str | None) -> Path:
    if not raw:
        raise RenderError(
            "no framework root supplied — pass --framework-dir <path>; it is the cwd every "
            "rendered hook pins and the anchor the harness reads from the environment"
        )
    root = Path(raw).expanduser()
    if not root.is_dir():
        raise RenderError(f"the framework root does not exist: {root}")
    return root.resolve()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Render an adapter's hooks.yaml into an installable host hook file."
    )
    parser.add_argument("--env", required=True, help="adapter environment id under adapters/")
    parser.add_argument("--framework-dir", help="absolute framework root; becomes every hook cwd")
    parser.add_argument(
        "--dest",
        help="directory to install into; defaults to <framework-dir>/.github/hooks",
    )
    parser.add_argument("--hooks", help="hook map to render; defaults to adapters/<env>/hooks.yaml")
    parser.add_argument(
        "--agent-hooks",
        help="H0 agent hook template; defaults to adapters/<env>/agent-hooks.yaml",
    )
    parser.add_argument(
        "--settings",
        help="required-settings map; defaults to adapters/<env>/settings.yaml",
    )
    parser.add_argument(
        "--settings-dest",
        help="directory holding the workspace settings file; defaults to the location the "
        "settings map names, under <framework-dir>",
    )
    parser.add_argument(
        "--bundle-dir",
        help="root of the host bundle the framework's agents are DELIVERED from; the H0 "
        "block is injected there, in place, on top of the bundle's own frontmatter",
    )
    parser.add_argument(
        "--agents-dir",
        help="agent sources to render from; defaults to <bundle-dir>/agents",
    )
    parser.add_argument(
        "--agents-dest",
        help="directory the rendered agents land in; defaults to <bundle-dir>/agents",
    )
    parser.add_argument(
        "--workflows-dir",
        help="workflow catalog naming the orchestrators; defaults to <framework-dir>/conf/workflows",
    )
    args = parser.parse_args(argv)

    adapters_dir = Path(__file__).resolve().parent
    try:
        framework_root = _resolve_framework_root(args.framework_dir)
        hooks_source = Path(args.hooks) if args.hooks else adapters_dir / args.env / "hooks.yaml"
        agent_hooks_source = (
            Path(args.agent_hooks)
            if args.agent_hooks
            else adapters_dir / args.env / AGENT_HOOKS_FILENAME
        )
        settings_source = (
            Path(args.settings) if args.settings else adapters_dir / args.env / SETTINGS_FILENAME
        )
        agents_dir = _resolve_agents_dir(args.agents_dir, args.bundle_dir, "read from")
        agents_dest = _resolve_agents_dir(args.agents_dest, args.bundle_dir, "written to")
        workflows_dir = (
            Path(args.workflows_dir)
            if args.workflows_dir
            else framework_root / "conf" / "workflows"
        )
        dest = Path(args.dest) if args.dest else framework_root / ".github" / "hooks"
        settings_dest = Path(args.settings_dest) if args.settings_dest else None

        hook_map = render(hooks_source, adapters_dir, framework_root)
        agents = render_agents(
            agent_hooks_source,
            agents_dir,
            agents_dest,
            workflows_dir,
            adapters_dir,
            framework_root,
        )
        settings_target, settings_text = render_settings(
            settings_source, framework_root, dest, settings_dest
        )
    except RenderError as error:
        print(f"render_hooks: {error}", file=sys.stderr)
        return 2

    # All three targets validated: only now does anything reach disk.
    dest.mkdir(parents=True, exist_ok=True)
    target = dest / RENDERED_FILENAME
    target.write_text(json.dumps(hook_map, indent=2) + "\n", encoding="utf-8")

    agents_dest.mkdir(parents=True, exist_ok=True)
    for path, text in agents.items():
        path.write_text(text, encoding="utf-8")

    if settings_text is not None:
        settings_target.parent.mkdir(parents=True, exist_ok=True)
        settings_target.write_text(settings_text, encoding="utf-8")

    print(f"installed: {target}")
    print(f"  rendered from: {hooks_source}")
    print(f"  framework root (hook cwd): {framework_root}")
    print(f"  dispatch: {adapters_dir / 'dispatch.sh'}")
    print(f"installed H0 agent-scoped registration ({len(agents)} orchestrator(s)):")
    for path in sorted(agents):
        print(f"  {path}")
    print(f"  rendered from: {agent_hooks_source} + {agents_dir}")
    if settings_text is None:
        print(f"settings already correct: {settings_target}")
    else:
        print(f"settings merged: {settings_target}")
        print(f"  rendered from: {settings_source}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
