#!/usr/bin/env python3
# Generic hook-registration renderer — shared by every environment adapter, exactly like
# dispatch.sh; nothing environment-specific lives in this file.
#
# An adapter's hooks.yaml is the SOURCE OF TRUTH for its firing surface, but it cannot be
# installed verbatim: the host executes a hook's `command` as a shell command line and
# resolves its `cwd` against $HOME by default, so both must be absolute by the time the host
# reads them. This script is that rendering stage.
#
# TWO render targets, one substitution path:
#   hooks.yaml        -> the workspace hook file, <dest>/safe-harness.json;
#   agent-hooks.yaml  -> a `hooks:` block in the frontmatter of one generated agent file per
#                        framework ORCHESTRATOR (the H0 session-started boundary, which the
#                        host reads per agent, never from the workspace file).
#
# Three placeholders are substituted:
#   {{ADAPTERS_DIR}}   this directory, derived from THIS FILE'S own location — `adapters/`
#                      ships in the harness repo, never in the framework, so anchoring the
#                      dispatch path on any environment variable would name a file that does
#                      not exist;
#   {{FRAMEWORK_DIR}}  the absolute framework root, supplied explicitly and required to exist.
#   {{AGENT_SLUG}}     the scoping orchestrator's slug (agent target only) — the trailing
#                      dispatch argument that carries the agent identity no payload names.
#
# Rendered output is machine-specific: it is generated at install time, never committed. The
# agent target therefore writes to a GENERATED agent file and reads the framework's committed
# agent sources without touching them; everything outside the managed block — frontmatter and
# body alike — is carried across byte for byte.
#
# Rendering is all-or-nothing — every output is validated in memory and files are written only
# once BOTH targets pass. A half-rendered registration is the failure this stage prevents.

import argparse
import json
import re
import shlex
import sys
from pathlib import Path

import yaml

RENDERED_FILENAME = "safe-harness.json"
AGENT_HOOKS_FILENAME = "agent-hooks.yaml"
_COMMAND_FIELD = "command"
_REQUIRED_FIELDS = ("type", "command", "cwd")
_PLACEHOLDER = re.compile(r"\{\{[^{}]*\}\}")
_HOOKS_KEY = "hooks"
_AGENT_HOOKS_KEY = "agentHooks"
_ORCHESTRATOR_KEY = "orchestrator"
_WORKFLOW_GLOB = "*.workflow.conf.yaml"
_FENCE = "---"
_BLOCK_OPEN = "# >>> safe-harness H0 — generated by adapters/render_hooks.py; do not edit >>>"
_BLOCK_CLOSE = "# <<< safe-harness H0 <<<"


class RenderError(Exception):
    """A rendering refusal — reported to the operator, never written to disk."""


def _substitute(node, shell_values: dict, plain_values: dict, in_command: bool):
    if isinstance(node, dict):
        return {
            key: _substitute(value, shell_values, plain_values, key == _COMMAND_FIELD)
            for key, value in node.items()
        }
    if isinstance(node, list):
        return [_substitute(item, shell_values, plain_values, in_command) for item in node]
    if isinstance(node, str):
        rendered = node
        # A `command` is a shell command line; every other field is a literal path.
        for placeholder, value in (shell_values if in_command else plain_values).items():
            rendered = rendered.replace(placeholder, value)
        return rendered
    return node


def _no_leftover_placeholder(rendered: str, where: str) -> None:
    leftover = sorted(set(_PLACEHOLDER.findall(rendered)))
    if leftover:
        raise RenderError(
            f"unsubstituted placeholder(s) survived rendering {where}: "
            + ", ".join(leftover)
            + " — this renderer resolves only {{ADAPTERS_DIR}}, {{FRAMEWORK_DIR}}"
            + " and {{AGENT_SLUG}}"
        )


def _validate_hooks(hooks, where: str) -> None:
    if not isinstance(hooks, dict) or not hooks:
        raise RenderError(f"{where} has no '{_HOOKS_KEY}' object")

    for event, entries in hooks.items():
        if not isinstance(entries, list) or not entries:
            raise RenderError(f"hook '{event}' registers no command entry")
        for index, entry in enumerate(entries):
            location = f"hook entry {event}[{index}]"
            if not isinstance(entry, dict):
                raise RenderError(f"{location} is not an object")

            missing = [field for field in _REQUIRED_FIELDS if field not in entry]
            if missing:
                raise RenderError(
                    f"{location} is missing required field(s): {', '.join(missing)}"
                )

            cwd = Path(entry["cwd"])
            if not cwd.is_absolute():
                raise RenderError(f"{location} has a relative cwd: {entry['cwd']}")
            if not cwd.is_dir():
                raise RenderError(
                    f"{location} has a cwd that is not a directory: {entry['cwd']}"
                )

            argv = shlex.split(entry[_COMMAND_FIELD])
            if not argv:
                raise RenderError(f"{location} has an empty command")

            program = Path(argv[0])
            if not program.is_absolute():
                raise RenderError(f"{location} has a relative command path: {argv[0]}")
            if not program.is_file():
                raise RenderError(f"{location} names a command that does not exist: {argv[0]}")


def _validate(hook_map: dict) -> None:
    _no_leftover_placeholder(json.dumps(hook_map), "the workspace hook map")
    _validate_hooks(hook_map.get(_HOOKS_KEY), "the hook map")


def _load_source(path: Path, what: str) -> dict:
    if not path.is_file():
        raise RenderError(f"no {what} at {path}")

    source = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(source, dict):
        raise RenderError(f"the {what} at {path} is not an object")
    return source


def _substituted(source, adapters_dir: Path, framework_root: Path, slug: str | None = None):
    literals = {
        "{{ADAPTERS_DIR}}": str(adapters_dir),
        "{{FRAMEWORK_DIR}}": str(framework_root),
    }
    if slug is not None:
        literals["{{AGENT_SLUG}}"] = slug
    return _substitute(
        source,
        shell_values={key: shlex.quote(value) for key, value in literals.items()},
        plain_values=literals,
        in_command=False,
    )


def _require_dispatch(adapters_dir: Path) -> None:
    dispatch = adapters_dir / "dispatch.sh"
    if not dispatch.is_file():
        raise RenderError(f"no dispatch script at {dispatch}")


def render(hooks_source: Path, adapters_dir: Path, framework_root: Path) -> dict:
    _require_dispatch(adapters_dir)
    rendered = _substituted(
        _load_source(hooks_source, "hook map"), adapters_dir, framework_root
    )
    _validate(rendered)
    return rendered


def _orchestrator_slugs(workflows_dir: Path) -> list[str]:
    """An orchestrator is whoever the framework's own workflow catalog names as one — the
    adapter hardcodes no roster."""
    if not workflows_dir.is_dir():
        raise RenderError(
            f"no workflow catalog at {workflows_dir} — the orchestrator set the H0 "
            "registration follows is derived from it"
        )

    slugs = set()
    for path in sorted(workflows_dir.glob(_WORKFLOW_GLOB)):
        workflow = yaml.safe_load(path.read_text(encoding="utf-8"))
        if not isinstance(workflow, dict):
            raise RenderError(f"the workflow at {path} is not an object")
        slug = workflow.get(_ORCHESTRATOR_KEY)
        if slug is not None:
            if not isinstance(slug, str) or not slug:
                raise RenderError(f"the workflow at {path} names a non-slug orchestrator")
            slugs.add(slug)

    if not slugs:
        raise RenderError(
            f"the workflow catalog at {workflows_dir} names no orchestrator — nothing "
            "would carry the H0 session-started registration and no session could open"
        )
    return sorted(slugs)


def _split_frontmatter(text: str, where: str) -> tuple[list[str], str]:
    lines = text.splitlines(keepends=True)
    if not lines or lines[0].strip() != _FENCE:
        raise RenderError(f"{where} has no YAML frontmatter to carry the hook block")

    for index in range(1, len(lines)):
        if lines[index].strip() == _FENCE:
            return lines[1:index], "".join(lines[index + 1 :])
    raise RenderError(f"{where} has a frontmatter block that is never closed")


def _without_managed_block(front: list[str], where: str) -> list[str]:
    kept: list[str] = []
    inside = False
    for line in front:
        marker = line.strip()
        if marker == _BLOCK_OPEN:
            if inside:
                raise RenderError(f"{where} carries a damaged managed hook block (nested)")
            inside = True
        elif marker == _BLOCK_CLOSE:
            if not inside:
                raise RenderError(f"{where} carries a damaged managed hook block (unopened)")
            inside = False
        elif not inside:
            kept.append(line)
    if inside:
        raise RenderError(f"{where} carries a damaged managed hook block (never closed)")
    return kept


def _render_agent(source_text: str, slug: str, hooks: dict, where: str) -> str:
    front, body = _split_frontmatter(source_text, where)
    front = _without_managed_block(front, where)

    declared = yaml.safe_load("".join(front)) or {}
    if not isinstance(declared, dict):
        raise RenderError(f"{where} has frontmatter that is not a YAML object")
    if _HOOKS_KEY in declared:
        raise RenderError(
            f"{where} already declares its own unmanaged '{_HOOKS_KEY}:' block — a second "
            "one would make the frontmatter a duplicate key the host rejects"
        )

    # `width` disables YAML line folding: a `command` is a shell command line the host runs
    # verbatim, and absolute paths routinely exceed the default 80-column fold.
    block = yaml.safe_dump(
        {_HOOKS_KEY: hooks},
        sort_keys=False,
        default_flow_style=False,
        allow_unicode=True,
        width=2**31 - 1,
    )
    rendered = (
        f"{_FENCE}\n"
        + "".join(front)
        + f"{_BLOCK_OPEN}\n"
        + block
        + f"{_BLOCK_CLOSE}\n"
        + f"{_FENCE}\n"
        + body
    )

    _no_leftover_placeholder(rendered, where)
    check_front, check_body = _split_frontmatter(rendered, where)
    parsed = yaml.safe_load("".join(check_front))
    if not isinstance(parsed, dict):
        raise RenderError(f"{where} rendered frontmatter that is not a YAML object")
    if parsed.get(_HOOKS_KEY) != hooks:
        raise RenderError(f"{where} rendered a hook block that does not match its source")
    if {key: value for key, value in parsed.items() if key != _HOOKS_KEY} != declared:
        raise RenderError(f"{where} rendered frontmatter that alters the agent's own keys")
    if check_body != body:
        raise RenderError(f"{where} rendered a body that differs from its source")
    _validate_hooks(hooks, where)
    return rendered


def render_agents(
    agent_hooks_source: Path,
    agents_dir: Path,
    agents_dest: Path,
    workflows_dir: Path,
    adapters_dir: Path,
    framework_root: Path,
) -> dict[Path, str]:
    """The H0 target: one rendered agent file per framework orchestrator, each carrying the
    agent-scoped `UserPromptSubmit` registration with its OWN slug as dispatch argument."""
    _require_dispatch(adapters_dir)

    source = _load_source(agent_hooks_source, "agent hook map")
    template = source.get(_AGENT_HOOKS_KEY)
    if not isinstance(template, dict) or not template:
        raise RenderError(
            f"the agent hook map at {agent_hooks_source} has no '{_AGENT_HOOKS_KEY}' object"
        )

    outputs: dict[Path, str] = {}
    for slug in _orchestrator_slugs(workflows_dir):
        agent_source = agents_dir / f"{slug}.agent.md"
        if not agent_source.is_file():
            raise RenderError(
                f"orchestrator '{slug}' has no agent file at {agent_source} — its "
                "session-started boundary would never fire"
            )
        hooks = _substituted(template, adapters_dir, framework_root, slug)
        outputs[agents_dest / f"{slug}.agent.md"] = _render_agent(
            agent_source.read_text(encoding="utf-8"), slug, hooks, str(agent_source)
        )
    return outputs


def _resolve_framework_root(raw: str | None) -> Path:
    if not raw:
        raise RenderError(
            "no framework root supplied — pass --framework-dir <path>; it is the cwd every "
            "rendered hook pins and the anchor the harness reads from the environment"
        )
    root = Path(raw).expanduser()
    if not root.is_dir():
        raise RenderError(f"the framework root does not exist: {root}")
    return root.resolve()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Render an adapter's hooks.yaml into an installable host hook file."
    )
    parser.add_argument("--env", required=True, help="adapter environment id under adapters/")
    parser.add_argument("--framework-dir", help="absolute framework root; becomes every hook cwd")
    parser.add_argument(
        "--dest",
        help="directory to install into; defaults to <framework-dir>/.github/hooks",
    )
    parser.add_argument("--hooks", help="hook map to render; defaults to adapters/<env>/hooks.yaml")
    parser.add_argument(
        "--agent-hooks",
        help="H0 agent hook template; defaults to adapters/<env>/agent-hooks.yaml",
    )
    parser.add_argument(
        "--agents-dir",
        help="agent sources to render from; defaults to <framework-dir>/agents",
    )
    parser.add_argument(
        "--agents-dest",
        help="directory the rendered agents land in; defaults to <framework-dir>/.github/agents",
    )
    parser.add_argument(
        "--workflows-dir",
        help="workflow catalog naming the orchestrators; defaults to <framework-dir>/conf/workflows",
    )
    args = parser.parse_args(argv)

    adapters_dir = Path(__file__).resolve().parent
    try:
        framework_root = _resolve_framework_root(args.framework_dir)
        hooks_source = Path(args.hooks) if args.hooks else adapters_dir / args.env / "hooks.yaml"
        agent_hooks_source = (
            Path(args.agent_hooks)
            if args.agent_hooks
            else adapters_dir / args.env / AGENT_HOOKS_FILENAME
        )
        agents_dir = Path(args.agents_dir) if args.agents_dir else framework_root / "agents"
        agents_dest = (
            Path(args.agents_dest)
            if args.agents_dest
            else framework_root / ".github" / "agents"
        )
        workflows_dir = (
            Path(args.workflows_dir)
            if args.workflows_dir
            else framework_root / "conf" / "workflows"
        )

        hook_map = render(hooks_source, adapters_dir, framework_root)
        agents = render_agents(
            agent_hooks_source,
            agents_dir,
            agents_dest,
            workflows_dir,
            adapters_dir,
            framework_root,
        )
    except RenderError as error:
        print(f"render_hooks: {error}", file=sys.stderr)
        return 2

    # Both targets validated: only now does anything reach disk.
    dest = Path(args.dest) if args.dest else framework_root / ".github" / "hooks"
    dest.mkdir(parents=True, exist_ok=True)
    target = dest / RENDERED_FILENAME
    target.write_text(json.dumps(hook_map, indent=2) + "\n", encoding="utf-8")

    agents_dest.mkdir(parents=True, exist_ok=True)
    for path, text in agents.items():
        path.write_text(text, encoding="utf-8")

    print(f"installed: {target}")
    print(f"  rendered from: {hooks_source}")
    print(f"  framework root (hook cwd): {framework_root}")
    print(f"  dispatch: {adapters_dir / 'dispatch.sh'}")
    print(f"installed H0 agent-scoped registration ({len(agents)} orchestrator(s)):")
    for path in sorted(agents):
        print(f"  {path}")
    print(f"  rendered from: {agent_hooks_source} + {agents_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
